<!doctype html>
<html>
    <head>
        <title>PHP Class List</title>
        <base href=/phpdocs/index.php/>
    </head>
    <body>
        <?php if (isset($class, $methods)): ?>
            <h1><?php echo $class?></h1>
            <h2>Methods</h2>
            <ul>
                <?php if($methods): ?>
                    <?php foreach($methods as $method): ?>
                        <li><?php echo $method; ?></li>
                    <?php endforeach; ?>
                <?php else: ?>
                    <li>This class has no methods</li>
                <?php endif; ?>
            </ul>
            <a href=classes>Back to class list</a>
        <?php endif; ?>
        <?php if(isset($classes)): ?>
            <h1>PHP Class List</h1>
            <?php foreach($classes as $className): ?>
                <li><a href=classes/<?php echo $className; ?>><?php echo $className; ?></a>
            <?php endforeach; ?>
        <?php endif; ?>
    </body>
</html>
