name: Continuous Integration

on:
  push: ~
  pull_request: ~

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.5"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Run Unit Tests
        run: vendor/bin/phpunit

  code-coverage:
    name: Code Coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          coverage: pcov

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Generate Code Coverage Report
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Send Code Coverage Report to Codecov.io
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  static-analysis:
    name: Static Analysis

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze
